apiVersion: apps/v1
kind: Deployment
metadata:
  name: redfish-exporter
  labels:
    app: redfish-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redfish-exporter
  template:
    metadata:
      labels:
        app: redfish-exporter
    spec:
      containers:
        - name: redfish-exporter
          image: redfish-exporter:local
          imagePullPolicy: Never
          ports:
            - containerPort: 9812
